# Generated by Django 4.1.7 on 2023-02-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satyanarayan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(height_field=100, upload_to='thumbnails', width_field=100)),
            ],
        ),
    ]
