# Generated by Django 4.1.7 on 2023-02-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satyanarayan', '0002_facilitie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitie',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
